module.exports = [
	// { value: 1, provincia: 16, label: 'Araba/Álava' },
	{ value: 2, provincia: 8, label: 'ALBACETE' },
	{ value: 3, provincia: 10, label: 'ALACANT' },
	{ value: 4, provincia: 1, label: 'ALMERIA' },
	{ value: 5, provincia: 7, label: 'AVILA' },
	{ value: 6, provincia: 11, label: 'BADAJOZ' },
	{ value: 7, provincia: 4, label: 'ILLES BALEARS' },
	{ value: 8, provincia: 9, label: 'BARCELONA' },
	{ value: 9, provincia: 7, label: 'BURGOS' },
	{ value: 10, provincia: 11, label: 'CACERES' },
	{ value: 11, provincia: 1, label: 'CADIZ' },
	{ value: 12, provincia: 10, label: 'CASTELLO' },
	{ value: 13, provincia: 8, label: 'CIUDAD REAL' },
	{ value: 14, provincia: 1, label: 'CORDOBA' },
	{ value: 15, provincia: 12, label: 'A CORUÑA' },
	{ value: 16, provincia: 8, label: 'CUENCA' },
	{ value: 17, provincia: 9, label: 'GIRONA' },
	{ value: 18, provincia: 1, label: 'GRANADA' },
	{ value: 19, provincia: 1, label: 'GUADALAJARA' },
	// { value: 20, provincia: 16, label: 'Gipuzkoa' },
	{ value: 21, provincia: 1, label: 'HUELVA' },
	{ value: 22, provincia: 2, label: 'HUESCA' },
	{ value: 23, provincia: 1, label: 'JAEN' },
	{ value: 24, provincia: 7, label: 'LEON' },
	{ value: 25, provincia: 9, label: 'LLEIDA' },
	{ value: 26, provincia: 17, label: 'LA RIOJA' },
	{ value: 27, provincia: 12, label: 'LUGO' },
	{ value: 28, provincia: 13, label: 'MADRID' },
	{ value: 29, provincia: 1, label: 'MALAGA' },
	{ value: 30, provincia: 14, label: 'MURCIA' },
	// { value: 31, provincia: 15, label: 'Navarra' },
	{ value: 32, provincia: 12, label: 'OURENSE' },
	{ value: 33, provincia: 3, label: 'ASTURIAS' },
	{ value: 34, provincia: 7, label: 'PALENCIA' },
	{ value: 35, provincia: 5, label: 'LAS PALMAS' },
	{ value: 36, provincia: 12, label: 'PONTEVEDRA' },
	{ value: 37, provincia: 7, label: 'SALAMANCA' },
	{ value: 38, provincia: 5, label: 'S.C. TENERIFE' },
	{ value: 39, provincia: 6, label: 'CANTABRIA' },
	{ value: 40, provincia: 7, label: 'SEGOVIA' },
	{ value: 41, provincia: 1, label: 'SEVILLA' },
	{ value: 42, provincia: 7, label: 'SORIA' },
	{ value: 43, provincia: 9, label: 'TARRAGONA' },
	{ value: 44, provincia: 2, label: 'TERUEL' },
	{ value: 45, provincia: 8, label: 'TOLEDO' },
	{ value: 46, provincia: 10, label: 'VALENCIA' },
	{ value: 47, provincia: 7, label: 'VALLADOLID' },
	// { value: 48, provincia: 16, label: 'Bizkaia' },
	{ value: 49, provincia: 7, label: 'ZAMORA' },
	{ value: 50, provincia: 2, label: 'ZARAGOZA' },
	{ value: 51, provincia: 18, label: 'CEUTA' },
	{ value: 52, provincia: 19, label: 'MELILLA' }
]